modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/CAS-ual-TY/Quorona/issues"

[[mods]]
    modId="the_floo"
    version="${file.jarVersion}"
    displayName="The Floo"
    displayURL="https://github.com/CAS-ual-TY/Quorona"
    logoFile="logo.png"
    credits="Mojang and the Minecraft Forge Team."
    authors="CAS_ual_TY"
    description="Highly infectious potion effect with mild symptoms. This mod was previously known as \"Quorona\"."
